### ISSUE TITLE
Get syntax error

### ISSUE THREAD

**Issue by greduan** [XCMer/fuzzy-window-switcher#22]
@XCMer Whenever I run `fuzzy-windows` from dmenu it doesn't work, so I tried using the CLI and it came back with the following:

```
 File "/usr/bin/fuzzy-windows", line 338
   print "Could not bind the hotkey:", config.hotkey
                                    ^
SyntaxError: invalid syntax
```

Is this an error in my configuration or a bug in fuzzy-window-switcher?

**Comment by XCMer** [comment]
I think you're trying to run it using Python 3. The print statement syntax is that of Python 2. Could you install Python 2.7 on the side and try running the script using it instead?

**Comment by greduan** [comment]
If I try to run it using Python 2 with `python2 /usr/bin/fuzzy-windows` I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/fuzzy-windows", line 2, in <module>
    import gi
ImportError: No module named gi
```

I installed it from the AUR BTW (I am using Arch Linux).

**Comment by XCMer** [comment]
Can you install the "python2-gobject" package in your system and try again?

**Comment by greduan** [comment]
OK installed that. Now when I run `python2 /usr/bin/fuzzy-windows` I just get empty output. What am I looking for? I'm using XMonad so that may have something to do with it?

Or is it required to use Ubuntu Unity?

**Comment by XCMer** [comment]
The default hotkey is F10. Try pressing it, and fuzzy windows should pop out.

**Comment by greduan** [comment]
Gotcha. Well it pops up but it doesn't list an windows, even if I type stuff... I tried opening it in a workspace with windows and another workspace without them, neither of them showed any windows.

**Comment by XCMer** [comment]
Hmm. That's weird. Without typing anything, the program should show you all the open windows. Have you created any config file for it? If not, then the problem would be something else. Gimme some time to figure this out.

**Comment by greduan** [comment]
I created a config file with the following:

```
[DEFAULT]
hotkey=F9
```

The file is located under `~/.fuzzy-windows`.

**Comment by XCMer** [comment]
I've still not been able to find a solution to this problem. The config file you've entered should not alter the windows shown. I'll try and see if I can find another Arch user.
