### ISSUE TITLE
Namespace Keybinder not available

### ISSUE THREAD

**Issue by eddie-dunn** [XCMer/fuzzy-window-switcher#24]
When I try to start fussy-windows:

```
$ ./fuzzy-windows
Traceback (most recent call last):
  File "./fuzzy-windows", line 5, in <module>
    gi.require_version('Keybinder', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Keybinder not available
```

Running Ubuntu 14.04.

**Comment by Frenzie** [comment]
Did you install keybinder 3?

**Comment by eddie-dunn** [comment]
Well, I have the package `python-keybinder` installed:

```
$ apt-cache policy python-keybinder
python-keybinder:
  Installed: 0.3.0-2
  Candidate: 0.3.0-2
  Version table:
 *** 0.3.0-2 0
        500 http://archive.ubuntu.com/ubuntu/ saucy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

 There's no Python keybinder 3 available in the repos, as far as I can tell:

```
$ apt-cache search keybinder
gir1.2-keybinder-0.0 - registers global key bindings for applications - introspection data
gir1.2-keybinder-3.0 - registers global key bindings for applications - typelib
keybinder-doc - registers global key bindings for applications - documentation
libkeybinder-3.0-0 - registers global key bindings for applications
libkeybinder-3.0-dev - registers global key bindings for applications - development headers
libkeybinder-dev - registers global key bindings for applications - development headers
libkeybinder0 - registers global key bindings for applications
python-keybinder - registers global key bindings for applications - Python bindings
```

**Comment by XCMer** [comment]
Can you try this? (Ref: http://www.webupd8.org/2013/07/fuzzy-window-switcher-for-ubuntu.html)
`sudo apt-get install libkeybinder-3.0-0 gir1.2-keybinder`

**Comment by eddie-dunn** [comment]
Yep, that solved it for me.
