### ISSUE TITLE
Cant't watch window frame and  'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by noorye4** [XCMer/fuzzy-window-switcher#25]
Hello
My OS is ubuntu 14.04 
python version 2.7.5

I just run "python fuzzy-window"

this is my screenshot
http://imgur.com/2ppx9cS

I can't see the fuzzy-window outside frame and I type and characters then I get the
trace back :

Traceback (most recent call last):
  File "fuzzy-windows", line 185, in enteredNameChanged
    self.windowList.rank(text)
  File "fuzzy-windows", line 94, in rank
    score += self.fuzzyMatcher.score(i['class_group'].lower())

I'm very like the software ,is helpful for me
thank you for replay

**Comment by Frenzie** [comment]
I'm not sure what you mean by outside frame, but you can increase the size of the window by putting something like the following in `~/.config/fuzzy-windows.conf`.

```
[DEFAULT] 
width=800
height=800
```

Additionally I find hiding everything except normal windows the most sensible way to use the program:

```
show_windows_normal=1
show_windows_desktop=0
show_windows_dock=0
show_windows_dialog=0
show_windows_toolbar=0
show_windows_menu=0
show_windows_utility=0
show_windows_splashscreen=0
```

Your screenshot is making me wonder whether there might be some issue with international characters, although simply opening some East-Asian page in my browser (for the title) does not seem to induce any crashes for me.

**Comment by vsiegel** [comment]
I think be outside frames he means the window decorations. 
(And I'm sure it's intentional to not show the decorations - I prefer it that way.)
But maybe there is a config value to enable them?

**Comment by Frenzie** [comment]
There is no configuration, but if you look on line 340 you can see `win.set_decorated(False)`. The default is `True`, so you can either change the value or comment it out.

It looks like with Gdk.Window you can also try [borders only](http://lazka.github.io/pgi-docs/Gdk-3.0/flags.html#Gdk.WMDecoration) (might need more than superficial edits), or you might use a [Gtk.Frame](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Frame.html) to fake borders (should be simpler).
